# Generated by Django 3.1.14 on 2022-06-26 05:10

import books.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
from  users.models.Audits import AuditModel
from  users.models.BaseModel import BaseModel


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boooks',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=200)),
                ('book_desc', models.CharField(max_length=400)),
                ('book_image', models.ImageField(upload_to='media')),
                ('date_of_publications', models.DateTimeField()),
                ('price', models.IntegerField()),
                ('chapters', djongo.models.fields.ArrayField(model_container=books.models.Chapters)),
                ('audit_status', djongo.models.fields.EmbeddedField(model_container=AuditModel)),
                ('entity_details', djongo.models.fields.EmbeddedField(model_container=BaseModel)),
                ('author', djongo.models.fields.ArrayReferenceField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
